Utils and infra helpers
AnyVisionltd/automation-infra pull request #406
Opened 2022-05-01 14:00 UTC by sagiL-oosto

- a new way to know which plugins are currently available for us
- new waiter util for checking when predicate gets stabilized

2022-05-01 15:38 UTC, OfirNAnyvision submitted a review, later dismissed

2022-05-09 07:22 UTC, camielAnyVision commented on infra/model/cluster.py
> +    def show_plugins(self):
best practice from pep?

2022-05-09 07:23 UTC, camielAnyVision requested changes
Pep for the show function

2022-05-25 11:36 UTC, camielAnyVision approved these changes

2022-05-25 11:36 UTC, camielAnyVision approved these changes

2022-05-25 11:41 UTC, merged